import Head from 'next/head'
import dynamic from 'next/dynamic'
import styles from '../styles/Home.module.scss'
import logo from '../assets/imgs/logo/logo.png'

const DynamicBasic = dynamic(() => import('../components/Basic/Basic'), {
  loading: () => 'Loading...',
})

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>PandaTron</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className={styles.space} />
      <DynamicBasic />
      <img className={styles.synthname} src={logo.src} alt='logo' />
    </div>
  )
}
